### ISSUE TITLE
Merging stores

### ISSUE THREAD

**Issue by GertKl** [undark-lab/swyft#101]
I have been trying for a while to merge separate stores (MemoryStore or DirectoryStore) with no luck. Is there a way to do this?

To be clear, what I want is to add the contents of one store to another, or possibly create a third store that contains the contents of both of the original two stores. I the end, I want to be able to train a network on a set of simulations that was split between two or more stores to begin with (for example because I made the stores for separate occasions, or created them in parallel for faster processing). I suspect there may be an easy answer, since this should be an essential functionality for facilitating simulation re-use (?), but I haven't been able to find it.

**Comment by bkmi** [comment]
Mathematically, this should be simple. Programmatically, it is not yet implemented.

It's a good idea and I'll add it as a feature request.

**Comment by bkmi** [comment]
Just to clarify this, https://arxiv.org/abs/2011.13951 should contain all the necessary math.

**Comment by cweniger** [comment]
v0.3 not further developed
