### ISSUE TITLE
Get marginal classifier with more than one observation key

### ISSUE THREAD

**Issue by erinaldi** [undark-lab/swyft#107]
Hi all,

I was trying to find out in the documentation how to use `swyft.get_marginal_classifier` to create a classifier for data/observation with more than one key in the dictionary.

Is that possible?
Or is it better to create a custom one?

Thank you.

**Comment by cweniger** [comment]
Hi Enrico,

I just looked at the code, and in that case, you would have to write your own custom one.

Best,
Christoph

**Comment by cweniger** [comment]
PS: We have another development version of swyft, which is based on pytorch-lightning, and meant to be much more flexible than the current version. If you want DM me and I'm happy to walk you through it (not documented much up to now, but we use it for a range of things already).  You can find it in the `lightning` branch.

**Comment by erinaldi** [comment]
@cweniger the pl stuff might be worth looking at. 
I can give it a try but I wouldn’t mind getting in touch with you and getting a short intro/tutorial.

**Comment by erinaldi** [comment]
@cweniger I sent you an email to the address I found on your GitHub profile. 
Thanks for the help.
