### ISSUE TITLE
Apply inverse transform to posterior samples?

### ISSUE THREAD

**Issue by bkmi** [undark-lab/swyft#12]
Right now, we generate posterior samples which are on the hypercube. Similarly, our plotting functions expect the truth to be on the hypercube as well. 

This is a bit odd since the user expects the parameter space to correspond to their prior, not the hypercube prior. If we wanted, reporting values on the actual prior could be automated when the user gives us `u(theta)` and `v(theta)`, where `u^{-1} = v`.

**Comment by bkmi** [comment]
Would you agree @cweniger that this should return `u` rather than `v`? Is this just a bug?

**Comment by cweniger** [comment]
@bkmi Indeed, everything should be returned in terms of v, not u. Why did you close this issue?

**Comment by bkmi** [comment]
I misunderstood how this works. We are expecting v to be returned I believe because `v` is what you call the physical parameter space and that's what the user expects.
