### ISSUE TITLE
Consistency between pre/post refactor

### ISSUE THREAD

**Issue by acole1221** [undark-lab/swyft#16]
I'm not sure whether I should expect consistent results between runs I made the the "pre-refactor" code and the refactor code, but I'm finding differences (refactor less accurate). 

Previously I would run 
```
s = swyft.NestedRatios(
        model,
        prior,
        noise=noise,
        obs=obs,
        device='cuda:0',
        Ninit=5000,
        cache=cache,
    )

s.run(
    max_rounds=1,
    train_args={'max_epochs': 50},
    head=Head10
    )
```
Where Head10 is a linear compression into 10 features. This gives me great results (I rescale the following plot via an expected 1-sigma)
![image](https://user-images.githubusercontent.com/6015516/114675722-db54d080-9d08-11eb-979c-7b59019ce383.png)

Now, I run what I believe to be the equivalent code
```
micro = swyft.Microscope(partitions, prior, obs, store = store, simhook = noise, device = 'cuda',
                        Ninit=5000,
                        head=Head10)
micro.focus(max_rounds=1)
```
which yields the analogous plot (same rescaling applied). 
![image](https://user-images.githubusercontent.com/6015516/114680863-e3fbd580-9d0d-11eb-9321-142d5d675866.png)
Note that I am not actually zooming, just training for one round. While the tip of the second plot is perhaps prettier, the 1 and 2 sigma are less accurate. Any ideas as to why this is happening?

**Comment by bkmi** [comment]
Do you know if there is a difference in total simulations generated when it converges?

If it isn't that, I am a bit suspicious about the new way points are selected. Maybe there is a bias to the training data.

**Comment by acole1221** [comment]
> Do you know if there is a difference in total simulations generated when it converges?
I am using 5000 simulations for both (although they are from different datastores, so different training data)

> If it isn't that, I am a bit suspicious about the new way points are selected. Maybe there is a bias to the training data.
Ok. As a check I re-ran with a new cache. Still seeing the same discrepancy. Curious.

**Comment by cweniger** [comment]
Hm, that is not expected. Do you have the notebooks somewhere to
double-check?  I could imagine that the head network is not used as
intended, or some of the default settings of the networks got effectively
changed when refactoring the code.

**Comment by acole1221** [comment]
good catch @cweniger! It looks like the option for non-default head and tail is not being passed to `posteriors.infer()` in `Microscope.zoom`. I directly tried `post.infer` with my `Head` and my posteriors are beautiful again:
![image](https://user-images.githubusercontent.com/6015516/114711227-ffc3a380-9d2e-11eb-8af0-43cbec66e1e8.png)
I'll push a bug fix and close the issue.
