### ISSUE TITLE
rename store to cache and fix saving, loading, and copying of cache (store)

### ISSUE THREAD

**Issue by bkmi** [undark-lab/swyft#19]
We use a cache. it is implemented in a zarr store. Calling them the same thing when they are conceptually different is confusing and leads to longer variable names. E.g. `store`, `zarr_store`, `zarr_memory_store` `memory_store` which is which? Exactly. 

What about when instantiating one or the other?
```python
def copy(self, sync_path=None):
    zarr_store = zarr.MemoryStore()
    zarr.convenience.copy_store(source=self.zarr_store, dest=zarr_store)
    return MemoryStore(
        params=self.params,
        zarr_store=zarr_store,
        simulator=self._simulator,
        sync_path=sync_path,
    )
```
Which one is the zarr store? Which one is our "MemoryStore" aka Cache?

We already had tests for saving and loading the caches. Please reinstate them and make the implementations comply with the spirit of the tests. (that might require rewriting the tests)

**Comment by cweniger** [comment]
Why I changed it: store implies something permanent, cache something temporary. I want that people use our cache/store for permanent storage, that's what it is made for, or at least the aspirational goal.

**Comment by acole1221** [comment]
To comment: as I work with swyft for some science problems with expensive simulators, I find myself reusing simulations from previous days for new inference rounds and to experiment with Head network structure. This "store" functionality regularly saves me ~30 minutes -- 1 hour. I can also imagine for "convergence" tests it is useful to think of this as a store.

I imagine the above scenario is our ideal use case. On the other hand, the "cache"/MemoryStore is perhaps more correct for evaluating swyft itself (running on toy simulators that are super fast).

**Comment by bkmi** [comment]
I see, that's a good reason to not use the word cache! I'm glad the long term storage is working for real science problems!

Just to clarify I have no particular attachment to the word cache. It's that I find name collisions in the code to be incredibly confusing (and anyone who is new will also find it confusing).

May I suggest we call it a warehouse, depot, repository, stockpile, stash, horde, supply, reserve, etc?

**Comment by cweniger** [comment]
Hm, I sort of like "store", and I like how it mirrors how Zarr MemoryStore and FileStore works.  But in the end I guess we would like to be backend independent.  We could just call it `Repo`, not sure.  But maybe there are also good ways to make this more transparent from the coding side and leave those names as they are.

Regarding `Dataset`, I simply think it is the best word for it.  It is the dataset that we use for training / validation etc.

Another alternative is to say `SwyftDataset`, `SwyftStore`, etc, but that is a bit redundant.

**Comment by cweniger** [comment]
What about `Vault`?
