### ISSUE TITLE
Progress monitoring for simulator and network training

### ISSUE THREAD

**Issue by adam-coogan** [undark-lab/swyft#20]
Since simulators and neural network training can be slow, it would be very helpful to add progress monitoring, possibly with [tqdm](https://github.com/tqdm/tqdm).

**Comment by acole1221** [comment]
I agree that progress monitoring currently leaves a bit to be desired. For simulations, it is possible using `dask`'s `ProgressBar` functionality: https://docs.dask.org/en/latest/diagnostics-local.html, e.g. 

```
with ProgressBar:
    dataset.simulate()
```

while monitoring the network training within a jupyter notbeook is possible by setting the `logger` to `DEBUG`, see e.g. https://stackoverflow.com/questions/18786912/get-output-from-the-logging-module-in-ipython-notebook. However, if you want to subsequently plot, you may have to be creative to keep from getting a flood of DEBUG message from matplotlib.

There is probably a more unified way to approach this. I think @bkmi changed the logging in the `paper` branch? https://github.com/undark-lab/swyft/tree/paper.
