### ISSUE TITLE
Make DirectoryStore & Dataset save to use

### ISSUE THREAD

**Issue by cweniger** [undark-lab/swyft#33]
Right now calling dataset on the store will write to the store if the wrong priors are specified. I suggest the following changes:
- Introduce `mode = 'r'` for directory store, so that we have a read-only configuration
- Make Dataset fail when points are requested that are not there (rather than adding them to the store).
- Add an additional `add` method to the store, which explicitly adds points for a given prior.
- Add some `check` method that allows to check whether a specific prior is already covered.
- Add some `info` method that provides information about the contained priors and associated number of samples in the store
- Add the ability to remove the latest prior and points.

**Comment by cweniger** [comment]
This would be closed by #38

**Comment by bkmi** [comment]
Hmm tbh this seems overly complicated. 

1. Why do we need modes at all if there is an add method? Unless add is called, it should be in read mode.
2. Good idea
3. Good idea
4. sure, why not
5. great idea
6. yeah, okay. is it necessary though?
