### ISSUE TITLE
Finalize and integrate DaskSimulator with DataStore

### ISSUE THREAD

**Issue by cweniger** [undark-lab/swyft#47]
Right now DaskSimulator is not used by default and has some stability issues. We need to test the dask setup carefully for a few use-cases with slow simulators.

**Comment by bkmi** [comment]
What's the status with this question?

**Comment by fnattino** [comment]
The issues that were raised concerning the DaskSimulator (#26 and #30) have been addressed. We  have made few tests and verified that the `DaskSimulator` can be used in place of the serial `Simulator` in the example notebooks. So, I would consider the integration complete. Unfortunately we did not have a use case with a slow simulator until now, so a real-world application on large scale has not been tested yet -  we are working to set this up right now..
