### ISSUE TITLE
Using different models in the same zarr storage?

### ISSUE THREAD

**Issue by rogerkuou** [undark-lab/swyft#57]
This is a follow-up question we have for issue #30.  created this issue just to keep this question documented. In #30, the Zarr storage was started from an incorrect model, and we want to continue using the same storage after correcting the model. 

This makes me wonder if we are potentially facing a case where the original model was correct, and we want to change the model but keep using the same storage?

**Comment by cweniger** [comment]
Inactive. Reopen if still relevant.
