### ISSUE TITLE
Potential storage corruption of the storage

### ISSUE THREAD

**Issue by rogerkuou** [undark-lab/swyft#58]
This is a related issue of #30. In #30 we fixed updating the storage status when a simulation fails within the `model`. However, this does not solve some specific cases. For example, if there is a keyboard interruption occurring within the `model` execution, the try-catch part will not be reached. In this case, the storage status of those simulations will stay `Running`. This can potentially corrupt storage.

A possible solution is to add a manual clean-up function to `storage` to remove the stalled simulations. One can also think of filtering out the stalling simulations by the time stamp of simulations.

**Comment by bkmi** [comment]
@rogerkuou is this solved?

**Comment by fnattino** [comment]
Hi @bkmi, this is something we thought about after looking at #30. Suppose your simulator is set up incorrectly and you end up with a store that contains some failed simulations together with some sound simulations. At the moment there is no utility function to delete a subset of samples from the store (say, provided their indices). I guess one could easily add a method to erase the points, but I aim not sure how one should deal with the intensity function(s)?

Overall I this might be a nice feature to have, but not top-priority for now?

**Comment by cweniger** [comment]
Inactive. Reopen if still an issue.
