### ISSUE TITLE
Introduce greater modularity into swyft by clarifying the roles of subsections

### ISSUE THREAD

**Issue by bkmi** [undark-lab/swyft#6]
# What do we have now? What do we want?
As it stands, there is essentially only one access point to `swyft` and that is via `NestedRatios`. Having this interface is acceptable; however, it would be better if `NestedRatios` was built out of smaller pieces which clearly delineate which aspect of the inference process they accomplish. Furthermore, users could then define their own version of `NestedRatios` which suits their needs.

# Definitions

I will introduce a few terms to clarify what I mean. The _Problem_ is defined by everything necessary to compute the exact posterior theoretically, namely the prior, the simulator, and the observation. A another structure will be called the _Task_, i.e. **a prior** and the simulator. (Emphasis could be another prior, namely a constrained prior.) In order to approximate the posterior for the _problem_, `NestedRatios` solves a series of _tasks_, the previous one defining the next _task's_ prior. Each of those tasks is solved using ratio estimation, abstractly this could be called an _Algorithm_. We call `NestedRatios`, the method used to solve the _problem_ a _strategy_.

# The Workflow

From a conceptual point of view, every part (`simulator`, `prior`, `observation`) of a _problem_ is independent and should be separated in code. This is what we are actually trying to solve, our "true beliefs" are reflected in the prior.

An _algorithm_ consumes a _task_ (either conceptually or programmatically) and produces an estimated ratio. In combination with an observation, we can then use that estimated ratio either for inference, to define a posterior, or to define a constrained prior, yielding a new _task_. The details of when to do what, defines out _strategy_.

# Technical Aspects / Data Structures

Previously I said,
> (a) The `prior`, `constrained prior`, and the `posterior` are all marginalized probability distributions. Their similarity suggests a similar API; however, instantiation must be different for each.

but I update my statement to
(a1) The `prior` and `constrained prior` are general (factorizable) distributions. It would be nice to use some common APIs rather than "reinventing the square wheel.
(a2) The `posterior` is ONLY a marginalized probability distribution. Although it would be good to have a similar API, it will need to be custom since each marginal must be dealt with separately. 

(b) In order to reduce calls to the simulator, we utilize the `cache`. Drawing from the cache is implicitly drawing from the joint distribution p(x, theta). Fundamentally, it is a database where parameter samples and corresponding simulations are stored. Dealing with accessing this should be abstracted from its use. If I have a `prior`, implemented using a `cache`, I want to be able to treat the `prior` just like a normal marginalized probability distribution.

(c) A `simulator`, a prior, and the neural network define ratio estimation. The output is a sort of "proto-posterior." A trained `RatioEstimator`, combined with an observation and a prior, should produce a posterior. One ought to be able to define a constrained prior by excluding regions of low probability from this posterior.

(d) This is where it loops around. We can define a constrained prior, given a `RatioEstimator`, prior, and an observation since we still have the simulator. These two (simulator, constrained prior) produce a new _task_. At this highest level, utilizing only calls to constituent structures, we can recreate the _strategy_ `NestedRatios`.

# Clarification about existing code

This document outlines the workflow and highlights technical challenges. How are these technical challenges overcome in the code as it exists now? I have grouped swyft into subfolders so that each part is somewhat separated from the other parts. Here I enumerate which part is which.

(a) The folder `swyft/marginals` hopes to accomplish this. Given (a1) and (a2), perhaps this should be divided between the two cases.

(b) This is currently divided between `swyft/cache` and `swyft/ip3`. `swyft/cache` should handle actually dealing with the database while `swyft/ip3` deals with the mathematical aspects that allow for the prior to be reformulated as a Poisson Point Process. Ideally, this "underwrites" prior and is mostly invisible to the user.

(c) This is all in `swyft/inference`, including the subfolders. The subfolders are there to separate out the training / design / hyperparameters of the algorithm and the execution of the algorithm.

(d) Right now this is just the file `swyft/nestedratios.py`.

The rest, including `swyft/nn`, `swyft/utils`, `swyft/plot.py` are minimal NN pieces, very broad utilities, and  the plotting scripts respectively. These could also use a refactor, but I think it only makes sense once we've accomplished the above.

**Comment by cweniger** [comment]
Thanks for the excellent summary!  Regarding point (b) of the technical summary, could you please clarify where you see similarities between the general posterior/prior class referred to in (a) and the way we sample from the cache? I think a similar interface would only work if instead of PDFs we start talking about intensities.  Otherwise 1000 samples from what is described in (a) will always yield 1000 samples, whereas 1000 samples from the cache only generates N ~ Pois(1000) samples.  How do you suggest to overcome this?

**Comment by bkmi** [comment]
I think you raise a good point. I was just rethinking this and going to edit my post, but I see you've already responded. Leaving it for tomorrow morning.

Main point is that sampling from the prior is actually a bit different that the posterior.

We could either provide a prior which, when you sample from it, returns Pois(1000) samples from the cache. Or, probably better, we make this explicit by revealing something like the intensity function.

**Comment by cweniger** [comment]
I think it would be good to avoid revealing the intensity function. I believe this is more confusing for most people than just saying that we sample ~1000 samples from some PDF. Regarding draws from priors, constrained priors, and priors sampled through the cache, we could always have the same interface, with the only difference that in the last case the number of samples that we get is stochastic. In order to make this difference explicit, we could use different variable names (N and N_req?).

The big difference between posteriors samples and prior samples will be that posterior samples should include weights by default. This is important for efficiently plotting posteriors. Replacing the weights with w=1 using rejection sampling is computationally heavier, and can be a serious bottleneck in some cases.  Since those weights will also depend on the particular marginal (as it does now), the output format of posteriors is simply different from the output format of priors. We can emphasize that distinction by using different names, or even data classes, for the output.  (Samples vs WeightedSamples?).

**Comment by bkmi** [comment]
First of all, I updated my first post to reflect our discussion. Namely, you're correct. We should be careful about the difference between the cache, prior, and posterior, and I was not being careful enough.

Secondly, I agree let's hide the intensity function. Maybe we can do it by separating out a cache class which has the features of (a) evaluating the prior (b) sampling from the prior (c) sampling from p(x, z) using the simulator and (d) all the other features it currently has.

Regarding the "primary return object:" the marginal posterior. The marginal posterior ought to (a) be evaluated marginally (b) can sample p(theta | x) marginally. The so-called "weighted samples" are just posterior evaluations of samples drawn via the prior. I think it would be a good idea to have the output of the RatioEstimator be a marginalized distribution object which has these features including the requested (c) weighted prior sample feature. All of these features would be methods for a MarginalizedDistribution object. It's just better conceptually to have a MarginalizedDistribution than returning that distribution evaluated on some samples.
