### ISSUE TITLE
RuntimeError in Examples - 1. Head networks

### ISSUE THREAD

**Issue by samgagnon** [undark-lab/swyft#60]
I am running swyft on an environment with pytorch 1.9.0 and swyft 0.2.0 installed. The example Jupyter notebooks all fail when post.train() is called. The notebook `Examples - 1. Head networks` returns the following stack trace in cell 11:

`---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
~\Anaconda3\envs\nre\lib\site-packages\torch\utils\data\dataloader.py in _try_get_data(self, timeout)
    989         try:
--> 990             data = self._data_queue.get(timeout=timeout)
    991             return (True, data)

~\Anaconda3\envs\nre\lib\queue.py in get(self, block, timeout)
    177                     if remaining <= 0.0:
--> 178                         raise Empty
    179                     self.not_empty.wait(remaining)

Empty: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-13-5b3f12878c61> in <module>
      1 marginals = [0, 1, 2]
      2 post.add(marginals, device = DEVICE, head = Head)
----> 3 post.train(marginals, max_epochs = 10)

~\Anaconda3\envs\nre\lib\site-packages\swyft\inference\posteriors.py in train(self, marginals, batch_size, validation_size, early_stopping_patience, max_epochs, optimizer, optimizer_args, scheduler, scheduler_args, nworkers, non_blocking)
    149         )
    150 
--> 151         re.train(self._dataset, trainoptions)
    152 
    153     def train_diagnostics(self, marginals: MarginalsType):

~\Anaconda3\envs\nre\lib\site-packages\swyft\inference\ratios.py in train(self, dataset, trainoptions)
     97         self.tail.train()
     98 
---> 99         diagnostics = trainloop(
    100             head=self.head,
    101             tail=self.tail,

~\Anaconda3\envs\nre\lib\site-packages\swyft\inference\train.py in trainloop(head, tail, dataset, trainoptions, device)
    204         drop_last=True,
    205     )
--> 206     tl, vl, sd_head, sd_tail = do_training(
    207         head, tail, train_loader, valid_loader, trainoptions, device
    208     )

~\Anaconda3\envs\nre\lib\site-packages\swyft\inference\train.py in do_training(head, tail, train_loader, validation_loader, trainoptions, device)
    109         head.train()
    110         tail.train()
--> 111         train_loss = do_epoch(train_loader, True)
    112         train_losses.append(train_loss / n_train_batches)
    113 

~\Anaconda3\envs\nre\lib\site-packages\swyft\inference\train.py in do_epoch(loader, train)
     75         training_context = suppress() if train else torch.no_grad()
     76         with training_context:
---> 77             for batch in loader:
     78                 optimizer.zero_grad()
     79                 sim, z, _ = batch

~\Anaconda3\envs\nre\lib\site-packages\torch\utils\data\dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

~\Anaconda3\envs\nre\lib\site-packages\torch\utils\data\dataloader.py in _next_data(self)
   1184 
   1185             assert not self._shutdown and self._tasks_outstanding > 0
-> 1186             idx, data = self._get_data()
   1187             self._tasks_outstanding -= 1
   1188             if self._dataset_kind == _DatasetKind.Iterable:

~\Anaconda3\envs\nre\lib\site-packages\torch\utils\data\dataloader.py in _get_data(self)
   1140         elif self._pin_memory:
   1141             while self._pin_memory_thread.is_alive():
-> 1142                 success, data = self._try_get_data()
   1143                 if success:
   1144                     return data

~\Anaconda3\envs\nre\lib\site-packages\torch\utils\data\dataloader.py in _try_get_data(self, timeout)
   1001             if len(failed_workers) > 0:
   1002                 pids_str = ', '.join(str(w.pid) for w in failed_workers)
-> 1003                 raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
   1004             if isinstance(e, queue.Empty):
   1005                 return (False, None)

RuntimeError: DataLoader worker (pid(s) 2540, 17392) exited unexpectedly`

Am I simply running the wrong version of pytorch or swyft? What is the origin of this error?

**Comment by samgagnon** [comment]
The fix here is the set the nworkers argument of post.train() equal to zero.

**Comment by bkmi** [comment]
Thanks for posting the workaround, obviously it would be ideal to be able to use `nworkers != 0`. May I ask, are you familiar with pytorch? Do you get this bug when using pytorch's dataloader?

**Comment by samgagnon** [comment]
Thanks for reaching out to me. I just tested this, and it looks like the
problem persists on pytorch itself. It seems like it's an issue with the
multiprocessing context. Is there a particular version of pytorch I
should use with swyft?

-Sam
