### ISSUE TITLE
zarr storage is slow

### ISSUE THREAD

**Issue by bkmi** [undark-lab/swyft#61]
EDITED:
DirectoryStore is slow, presumably due to saving to disk. However, MemoryStore is also really slow using some parameters. (namely when you use it for a dataset which does not have any parallelism, or few threads `nworkers=0` or `nworkers=1`.)

We need to figure out why and how the user can avoid this behavior.

ask me for proof of this if you need.

**Comment by fnattino** [comment]
Hi @bkmi , by any chance have you tried to increase the chunk size (`chunksize` argument when initialising the store)? The default value of 1 might not be optimal (I think suggested values are such that each chunk is ~100 MB).

**Comment by cweniger** [comment]
Performance depends on the details. For very simple data, and very simple networks, the stores are the bottleneck. If you have a way to improve that, I would be very happy to hear more. For reasonably complex data (images, with CNN embedding network, for example), GPU loads are high (between 50% and 100%), which seems to indicate that in that case training is the bottleneck.

Regarding the comment from fnattino, chuncksize is indeed important. But please keep it at 1.  We use random access. Any larger chuncksize degrades performance.

**Comment by bkmi** [comment]
This is a big problem. It is absurd how long it takes to load data using this storage method. It is an issue with memory store as well. 

A simple example. The store has 100,000 items in it. Each is a 2084 vector. There is only one processor used in loading the data.

It takes 10s per loop. This is something which should be imperceptibly fast. I can make another example if you need it but I recommend just filling a store with random values and trying to calculate the mean of a subset of them.

```python
%%timeit

dataset_ = swyft.Dataset(
    1024, 
    prior, 
    store, 
    simhook=inject_polarizations,
)

loader = torch.utils.data.DataLoader(
    dataset_,
    batch_size=512,
    num_workers=0,
    shuffle=False,
)

mean = 0.
meansq = 0.
for data in loader:
    xxx = data[0]["time_domain_strain"]
    vvv = data[0]["time_domain_strain"]
    mean = xxx.mean(dim=0)
    meansq = (xxx**2).mean(dim=0)

std = torch.sqrt(meansq - mean**2)
print("mean: " + str(mean))
print("std: " + str(std))
print()
```

**Comment by bkmi** [comment]
Maybe we need an object that lives between store and dataset? I think it's likely that accessing zarr with `Dataset` is just too slow.

**Comment by cweniger** [comment]
v0.4 ZarrStore is more minimal and very fast. The v0.3 store might be finally moved to future versions. For now I close this issue.
