### ISSUE TITLE
Make Head and Tail networks simpler.

### ISSUE THREAD

**Issue by cweniger** [undark-lab/swyft#63]
Right now both head and tail networks have quite some boiler plate code, and inherit from swyft.Module. This needs to change in order to make the code more accessible.

Proposed changes:
- Inherit from torch.Module
- n_features and calling super().__init__() will become irrelevant
- Save initialization parameters together with ratios, instead as part of the network
- The connection layer between head and tail should be decoupled from the tail, making it much easier to define custom tails.

**Comment by bkmi** [comment]
This will be addressed in the simplify branch.
