### ISSUE TITLE
HDI ValueError in plot.py

### ISSUE THREAD

**Issue by CHBKoenders** [undark-lab/swyft#64]
First off, this issue only occurs when the model has high certainty (probably due to overfitting, or too simple a problem). 

The problem can occur in lines 123-125.  This is because `zm[v > levels[i]]` can be empty if `v` has all the mass in one bin. This can be fixed by changing to `>=`.  Maybe even better to do a try catch with a message to increase the number of bins or check for overtraining.

-Kees

**Comment by bkmi** [comment]
Nice find! I'll take a look.

**Comment by cweniger** [comment]
Stalled? Closing now.
