### ISSUE TITLE
support dependent priors

### ISSUE THREAD

**Issue by bkmi** [undark-lab/swyft#72]
This is done within dynesty in the following manner:
https://dynesty.readthedocs.io/en/latest/quickstart.html#example-conditional-priors

It's a bit more complicated for us to do this because we have to consider marginalizing over them.

**Comment by bkmi** [comment]
For inspiration, consider the [dynesty implementation of Priors](https://github.com/joshspeagle/dynesty/blob/9fc19cfeec17ce3d87ba16c962e6ca59cd21d548/priors.py).

We need to be able to collect several distributions together for a prior, including dependent ones... but still have access to cdf, icdf, and log_prob at a minimum.

**Comment by bkmi** [comment]
One option is to require that new distributions subclass pytorch distribution, but that seems a bit excessive to me.

**Comment by cweniger** [comment]
In v0.4 hierarchical models with dependent priors can be straightforwardly implemented.
