### ISSUE TITLE
simulator test still not passing (sometimes)

### ISSUE THREAD

**Issue by bkmi** [undark-lab/swyft#87]
See the report here:
https://github.com/undark-lab/swyft/actions/runs/1476614939/attempts/1

My guess is that there is a timeout followed by a problem with a fragile command
```
def get_output(stdout, _):
    return {"sum": float(stdout)}
```

When I ran it again, it worked.
https://github.com/undark-lab/swyft/actions/runs/1476614939

Is there a way to make this test less stochastic?

**Comment by rogerkuou** [comment]
Hi @bkmi, thanks for addressing this! I fixed this in PR#88.

Indeed this is happening with float/str transforming but in the part of the `set_input` function. Essentially, this is caused y `bc` not accepting the scientific notation. So when we have a very small number e.g. 0.00123, NumPy will wrap it to 1.23e-3, which will be directly formatted to string, and not accepted by the Shell command `bc`.

As a solution, I forced the transforming to decimal format. I specifically tested this with a failing case and it works.
